// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/Fulcrum-Informante.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
	NuevoValor    string `protobuf:"bytes,3,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Fulcrum_Informante_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Fulcrum_Informante_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_proto_Fulcrum_Informante_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *City) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

func (x *City) GetNuevoValor() string {
	if x != nil {
		return x.NuevoValor
	}
	return ""
}

type Clock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reloj []int32 `protobuf:"varint,1,rep,packed,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *Clock) Reset() {
	*x = Clock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Fulcrum_Informante_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clock) ProtoMessage() {}

func (x *Clock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Fulcrum_Informante_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clock.ProtoReflect.Descriptor instead.
func (*Clock) Descriptor() ([]byte, []int) {
	return file_proto_Fulcrum_Informante_proto_rawDescGZIP(), []int{1}
}

func (x *Clock) GetReloj() []int32 {
	if x != nil {
		return x.Reloj
	}
	return nil
}

type DelCt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
}

func (x *DelCt) Reset() {
	*x = DelCt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Fulcrum_Informante_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCt) ProtoMessage() {}

func (x *DelCt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Fulcrum_Informante_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCt.ProtoReflect.Descriptor instead.
func (*DelCt) Descriptor() ([]byte, []int) {
	return file_proto_Fulcrum_Informante_proto_rawDescGZIP(), []int{2}
}

func (x *DelCt) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *DelCt) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

type NumClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rebeldes int32   `protobuf:"varint,1,opt,name=rebeldes,proto3" json:"rebeldes,omitempty"`
	Reloj    []int32 `protobuf:"varint,2,rep,packed,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *NumClock) Reset() {
	*x = NumClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Fulcrum_Informante_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumClock) ProtoMessage() {}

func (x *NumClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Fulcrum_Informante_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumClock.ProtoReflect.Descriptor instead.
func (*NumClock) Descriptor() ([]byte, []int) {
	return file_proto_Fulcrum_Informante_proto_rawDescGZIP(), []int{3}
}

func (x *NumClock) GetRebeldes() int32 {
	if x != nil {
		return x.Rebeldes
	}
	return 0
}

func (x *NumClock) GetReloj() []int32 {
	if x != nil {
		return x.Reloj
	}
	return nil
}

var File_proto_Fulcrum_Informante_proto protoreflect.FileDescriptor

var file_proto_Fulcrum_Informante_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2d,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x73, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x69,
	0x75, 0x64, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f,
	0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x1d, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x72,
	0x65, 0x6c, 0x6f, 0x6a, 0x22, 0x53, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x43, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63,
	0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x43, 0x69, 0x75, 0x64, 0x61, 0x64, 0x22, 0x3c, 0x0a, 0x08, 0x4e, 0x75, 0x6d,
	0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x32, 0x23, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x43, 0x69,
	0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x43, 0x69, 0x74, 0x79, 0x12, 0x05, 0x2e,
	0x43, 0x69, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x32, 0x2a, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x06, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x74,
	0x1a, 0x06, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x32, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x06,
	0x2e, 0x44, 0x65, 0x6c, 0x43, 0x74, 0x1a, 0x09, 0x2e, 0x4e, 0x75, 0x6d, 0x43, 0x6c, 0x6f, 0x63,
	0x6b, 0x32, 0x2c, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x61, 0x72, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x12, 0x05, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x32,
	0x2d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0c, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x05, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Fulcrum_Informante_proto_rawDescOnce sync.Once
	file_proto_Fulcrum_Informante_proto_rawDescData = file_proto_Fulcrum_Informante_proto_rawDesc
)

func file_proto_Fulcrum_Informante_proto_rawDescGZIP() []byte {
	file_proto_Fulcrum_Informante_proto_rawDescOnce.Do(func() {
		file_proto_Fulcrum_Informante_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Fulcrum_Informante_proto_rawDescData)
	})
	return file_proto_Fulcrum_Informante_proto_rawDescData
}

var file_proto_Fulcrum_Informante_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_Fulcrum_Informante_proto_goTypes = []interface{}{
	(*City)(nil),     // 0: City
	(*Clock)(nil),    // 1: Clock
	(*DelCt)(nil),    // 2: DelCt
	(*NumClock)(nil), // 3: NumClock
}
var file_proto_Fulcrum_Informante_proto_depIdxs = []int32{
	0, // 0: AddCity.AddCity:input_type -> City
	2, // 1: DeleteCity.DeleteCity:input_type -> DelCt
	2, // 2: GetNumberRebels.GetNumberRebels:input_type -> DelCt
	0, // 3: UpdateName.CambiarNombre:input_type -> City
	0, // 4: UpdateNumber.CambiarValor:input_type -> City
	1, // 5: AddCity.AddCity:output_type -> Clock
	1, // 6: DeleteCity.DeleteCity:output_type -> Clock
	3, // 7: GetNumberRebels.GetNumberRebels:output_type -> NumClock
	1, // 8: UpdateName.CambiarNombre:output_type -> Clock
	1, // 9: UpdateNumber.CambiarValor:output_type -> Clock
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Fulcrum_Informante_proto_init() }
func file_proto_Fulcrum_Informante_proto_init() {
	if File_proto_Fulcrum_Informante_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Fulcrum_Informante_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Fulcrum_Informante_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Fulcrum_Informante_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Fulcrum_Informante_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Fulcrum_Informante_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_Fulcrum_Informante_proto_goTypes,
		DependencyIndexes: file_proto_Fulcrum_Informante_proto_depIdxs,
		MessageInfos:      file_proto_Fulcrum_Informante_proto_msgTypes,
	}.Build()
	File_proto_Fulcrum_Informante_proto = out.File
	file_proto_Fulcrum_Informante_proto_rawDesc = nil
	file_proto_Fulcrum_Informante_proto_goTypes = nil
	file_proto_Fulcrum_Informante_proto_depIdxs = nil
}
