// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PetitionClient is the client API for Petition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PetitionClient interface {
	Petition(ctx context.Context, in *PetitionReq, opts ...grpc.CallOption) (*IPFul, error)
}

type petitionClient struct {
	cc grpc.ClientConnInterface
}

func NewPetitionClient(cc grpc.ClientConnInterface) PetitionClient {
	return &petitionClient{cc}
}

func (c *petitionClient) Petition(ctx context.Context, in *PetitionReq, opts ...grpc.CallOption) (*IPFul, error) {
	out := new(IPFul)
	err := c.cc.Invoke(ctx, "/Petition/Petition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetitionServer is the server API for Petition service.
// All implementations must embed UnimplementedPetitionServer
// for forward compatibility
type PetitionServer interface {
	Petition(context.Context, *PetitionReq) (*IPFul, error)
	mustEmbedUnimplementedPetitionServer()
}

// UnimplementedPetitionServer must be embedded to have forward compatible implementations.
type UnimplementedPetitionServer struct {
}

func (UnimplementedPetitionServer) Petition(context.Context, *PetitionReq) (*IPFul, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Petition not implemented")
}
func (UnimplementedPetitionServer) mustEmbedUnimplementedPetitionServer() {}

// UnsafePetitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PetitionServer will
// result in compilation errors.
type UnsafePetitionServer interface {
	mustEmbedUnimplementedPetitionServer()
}

func RegisterPetitionServer(s grpc.ServiceRegistrar, srv PetitionServer) {
	s.RegisterService(&Petition_ServiceDesc, srv)
}

func _Petition_Petition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetitionServer).Petition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Petition/Petition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetitionServer).Petition(ctx, req.(*PetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Petition_ServiceDesc is the grpc.ServiceDesc for Petition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Petition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Petition",
	HandlerType: (*PetitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Petition",
			Handler:    _Petition_Petition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Informante-Broker.proto",
}
